### ISSUE TITLE
__UWPOCR_Log is not used

### ISSUE THREAD

**Issue by vanowm** [DanysysTeam/UWPOCR#6]
It seems `__UWPOCR_Log` is not being used
`_UWPOCR_Log` however, being executed by each function, but it does nothing.

**Comment by Danyfirex** [comment]
You need to enable it using 

`_UWPOCR_Log(__UWPOCR_Log)`

**Comment by vanowm** [comment]
Oh, I see.
Even though it's commented out in examples, maybe it should be mentioned in the docs too?

**Comment by hashimaziz1** [comment]
Where is the log file saved to? Doesn't seem to be the current directory as far as I can tell

**Comment by Danyfirex** [comment]
It does not save any log file.

Regards
